[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "ctfd-wrapper"
requires-python = ">=3.7"
version = "0.3.1"
description = "A python wrapper for the CTFd project"
dependencies = [ "toml==0.10.2",]
[[project.authors]]
name = "Sckathach"

